services:
  # Web service
  - type: web
    name: adeptly
    runtime: python
    buildCommand: bash render_build.sh
    startCommand: gunicorn webapp_project.render_wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: DJANGO_SETTINGS_MODULE
        value: webapp_project.settings_production
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: adeptly_db
          property: connectionString

databases:
  - name: adeptly_db
    databaseName: adeptly
    plan: free
