services:
  - type: web
    name: adeptly
    env: python
    buildCommand: bash init_render.sh
    startCommand: bash prestart.sh && gunicorn wsgi_handler:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: webapp_project.render
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: DISABLE_COLLECTSTATIC
        value: 1
      - key: PYTHON_VERSION
        value: 3.11
