services:
  - type: web
    name: adeptly
    env: python
    buildCommand: pip install -r requirements.txt && python manage.py migrate && python manage.py collectstatic --no-input
    startCommand: gunicorn wsgi_handler:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: webapp_project.render
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: False
      - key: PYTHON_VERSION
        value: 3.11
