# Generated by Django 4.2.10 on 2025-03-30 20:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('prompt', models.TextField()),
                ('choice_a', models.CharField(max_length=255)),
                ('choice_b', models.CharField(max_length=255)),
                ('choice_c', models.CharField(max_length=255)),
                ('choice_d', models.CharField(max_length=255)),
                ('correct_answer', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D')], max_length=1)),
                ('problem_diagram', models.ImageField(blank=True, null=True, upload_to='problem_diagrams/')),
                ('solution_diagram', models.ImageField(blank=True, null=True, upload_to='solution_diagrams/')),
                ('estimated_time_to_complete', models.IntegerField(help_text='Estimated time in minutes')),
                ('difficulty', models.IntegerField(choices=[(1, 'Very Easy'), (2, 'Easy'), (3, 'Medium'), (4, 'Hard'), (5, 'Very Hard')], default=3)),
                ('solved_by', models.ManyToManyField(blank=True, related_name='solved_problems', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Rank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserTopicStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience', models.IntegerField(default=0)),
                ('rank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adeptly.rank')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adeptly.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='topic_stats', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimated_time_to_complete', models.IntegerField(help_text='Estimated time in minutes')),
                ('was_completed', models.BooleanField(default=False)),
                ('correct_attempts', models.IntegerField(default=0)),
                ('incorrect_attempts', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('problems', models.ManyToManyField(related_name='training_sessions', to='adeptly.problem')),
                ('problems_completed', models.ManyToManyField(blank=True, related_name='completed_in_sessions', to='adeptly.problem')),
                ('topics_covered', models.ManyToManyField(related_name='covered_in_sessions', to='adeptly.topic')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='training_sessions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TopicExperienceEarned',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_earned', models.IntegerField()),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adeptly.problem')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adeptly.topic')),
                ('training_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adeptly.trainingsession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='topics',
            field=models.ManyToManyField(related_name='problems', to='adeptly.topic'),
        ),
    ]
